name: OSX

on:
  push:
  pull_request:

jobs:
  build:
    env:
      DISPLAY: ":99.0"  # arbitrary
      # GSETTINGS_SCHEMA_DIR_CONDA_BACKUP is somehow related to the following issue https://github.com/conda/conda/issues/9966
      GSETTINGS_SCHEMA_DIR_CONDA_BACKUP: "/usr/share/miniconda/envs/testenv/share/glib-2.0/schemas"
    runs-on: macos-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        numpy-version: ["1.20"]
        pyqt-version: ["5.12"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

#    - uses: conda-incubator/setup-miniconda@v2
#      with:
#        channels: conda-forge
#        channel-priority: flexible
#        auto-update-conda: true
#        show-channel-urls: true
#        allow-softlinks: true
#        auto-activate-base: false
#        activate-environment: testenv
#        use-only-tar-bz2: false
#
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}

#    - name: Install Linux libraries
#      if: runner.os == 'Linux'
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y xvfb herbstluftwm
#
#    - name: Start 'xvfb'
#      if: runner.os == 'Linux'
#      run: |
#        sudo /sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
#        # sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
#        sleep 3
#
#    - name:  Start 'herbstluftwm'
#      if: runner.os == 'Linux'
#      run: |
#        herbstluftwm &
#        sleep 1

#    - name: Install packages
#      run: |
#        set -vxeuo pipefail
#
#        # conda update -y conda
#        conda list
#        pip list
#
#        conda install -y \
#          python=${{ matrix.python-version }} \
#          numpy=${{ matrix.numpy-version }} \
#          pyqt=${{ matrix.pyqt-version }} \
#          numba \
#          pip \
#          'scikit-beam>=0.0.24' \
#          -c conda-forge
#
#        # There are issues in building wheels for pystackreg>0.2.2 on OSX, so install pystackreg from CF
#        conda install -y pystackreg -c conda-forge
#
#        pip install --upgrade pip setuptools
#        pip install codecov
#        pip install -r requirements.txt
#        pip install -r requirements-dev.txt
#        pip install .
#        conda list
#        pip list
#
#    - name: Test with pytest
#      run: |
#        set -vxeuo pipefail
#        coverage run -m pytest -vv
#        coverage report
